#include "ui/fonts.h"

#include <cstddef>
#include <cstdio>

namespace ui {
namespace {

// Generated by xmake's utils.bin2c rule from ui/assets/fonts/. Embedded rather
// than shipped beside the exe because both families are SIL OFL and an app
// that cannot find its own font is an app that looks broken.
const unsigned char kArchivoRegular[] = {
#include "Archivo-Regular.ttf.h"
};
const unsigned char kArchivoMedium[] = {
#include "Archivo-Medium.ttf.h"
};
const unsigned char kArchivoSemiBold[] = {
#include "Archivo-SemiBold.ttf.h"
};
const unsigned char kArchivoBold[] = {
#include "Archivo-Bold.ttf.h"
};
const unsigned char kArchivoHeavy[] = {
#include "ArchivoExpanded-ExtraBold.ttf.h"
};
const unsigned char kFragmentMono[] = {
#include "FragmentMono-Regular.ttf.h"
};

Fonts g_fonts;

ImFont *AddFace(const unsigned char *data, size_t size, const char *name) {
	ImFontConfig cfg;
	// The arrays above live in .rdata for the life of the process, so the
	// atlas must not try to free them.
	cfg.FontDataOwnedByAtlas = false;
	cfg.SizePixels           = 0.0f;   // any size, rasterised on demand
	std::snprintf(cfg.Name, sizeof(cfg.Name), "%s", name);
	return ImGui::GetIO().Fonts->AddFontFromMemoryTTF(
	    const_cast<unsigned char *>(data), static_cast<int>(size), 0.0f, &cfg);
}

} // namespace

void Fonts::Load() {
	g_fonts.regular  = AddFace(kArchivoRegular, sizeof(kArchivoRegular), "Archivo Regular");
	g_fonts.medium   = AddFace(kArchivoMedium, sizeof(kArchivoMedium), "Archivo Medium");
	g_fonts.semibold = AddFace(kArchivoSemiBold, sizeof(kArchivoSemiBold), "Archivo SemiBold");
	g_fonts.bold     = AddFace(kArchivoBold, sizeof(kArchivoBold), "Archivo Bold");
	g_fonts.heavy    = AddFace(kArchivoHeavy, sizeof(kArchivoHeavy), "Archivo Expanded ExtraBold");
	g_fonts.mono     = AddFace(kFragmentMono, sizeof(kFragmentMono), "Fragment Mono");

	// Everything that does not name a face gets Archivo Regular.
	ImGui::GetIO().FontDefault = g_fonts.regular;
}

const Fonts &Fonts::Get() { return g_fonts; }

namespace {

TypeStyle Make(ImFont *font, float size, float lineHeight, float letterSpacing, bool mono) {
	return {font, size, PixelSizeFor(size, mono), lineHeight, letterSpacing};
}

} // namespace

TypeStyle StyleOf(Type role) {
	const Fonts &f = Fonts::Get();
	switch (role) {
	case Type::WindowHeading: return Make(f.heavy, 28.0f, 34.0f, -0.28f, false);
	case Type::DialogHeading: return Make(f.heavy, 22.0f, 28.0f, 0.0f, false);
	case Type::SectionTitle:  return Make(f.semibold, 15.0f, 20.0f, 0.0f, false);
	case Type::Body:          return Make(f.regular, 14.0f, 20.0f, 0.0f, false);
	case Type::BodySmall:     return Make(f.regular, 13.0f, 18.0f, 0.0f, false);
	case Type::FieldLabel:    return Make(f.semibold, 13.0f, 18.0f, 0.0f, false);
	case Type::Hint:          return Make(f.regular, 12.0f, 16.0f, 0.0f, false);
	case Type::MetaLabel:     return Make(f.semibold, 12.0f, 16.0f, 0.0f, false);
	case Type::ButtonPrimary: return Make(f.heavy, 17.0f, 22.0f, 0.17f, false);
	case Type::ButtonSmall:   return Make(f.semibold, 14.0f, 20.0f, 0.0f, false);
	case Type::MonoSmall:     return Make(f.mono, 12.0f, 16.0f, 0.0f, true);
	case Type::Mono:          return Make(f.mono, 13.0f, 20.0f, 0.0f, true);
	case Type::MonoLarge:     return Make(f.mono, 16.0f, 22.0f, 0.0f, true);
	case Type::Console:       return Make(f.mono, 12.5f, 20.0f, 0.0f, true);
	}
	return Make(f.regular, 14.0f, 20.0f, 0.0f, false);
}

ScopedType::ScopedType(Type role) {
	const TypeStyle s = StyleOf(role);
	ImGui::PushFont(s.font, s.pixelSize);
}

ScopedType::ScopedType(ImFont *font, float size) { ImGui::PushFont(font, size); }

ScopedType::~ScopedType() { ImGui::PopFont(); }

} // namespace ui
